# this was taken from https://github.com/JetBrains/swot

# pretty much all .de uni domains
uni_dict = {
    "gym-mellendorf.de": "Gymnasium Mellendorf",
    "uni-konstanz.de": "Universität Konstanz",
    "fhnon.de": "Fachhochschule Nordostniedersachsen",
    "katharineum.de": "Katharineum zu Lübeck",
    "uni-karlsruhe.de": "Universität Fridericana Karlsruhe (Technische Hochschule)",
    "mint-kolleg.de": "MINT-Kolleg Baden-Württemberg",
    "hs-koblenz.de": "Hochschule Koblenz",
    "fh-hildesheim.de": "Fachhochschule Hildesheim/Holzminden/Göttingen, Hochschule für angewandte Wissenschaft und Kunst",
    "adolfinum.de": "Gymnasium Adolfinum Moers",
    "sk-wadersloh.de": "Sekundarschule Wadersloh",
    "bbs-einbeck.de": "Berufsbildende Schulen Einbeck",
    "helmholtz-gymnasium.de": "Helmholtz-Gymnasium Essen",
    "siewerth-akademie.de": "Gustav-Siewerth-Akademie",
    "schiller-og.de": "Schiller Gymnasium Offenburg",
    "bs-gn.de": "Berufliche Schulen des Main-Kinzig-Kreises in Gelnhausen (Student accounts)",
    "fh-flensburg.de": "Hochschule Flensburg The old domain of Fachhochschule Flensburg, renamed to Hochschule Flensburg. The domain ist still in use for student email accounts.",
    "kag-erding.de": "Korbinian-Aigner-Gymnasium Erding",
    "evfh-nuernberg.de": "Evangelische Fachhochschule Nürnberg",
    "maxplanckschools.de": "Max Planck School of Cognition",
    "gbg-kaarst.de": "Georg-Büchner-Gymnasium Kaarst",
    "fh-muenster.de": "FH Muenster",
    "design-akademie-berlin.de": "design akademie berlin / SRH Hochschule für Kommunikation und Design",
    "kolleg-st-sebastian.de": "Kolleg St. Sebastian, Stegen",
    "bbs-buchholz.de": "BBS Buchholz Berufsbildende Schulen Buchholz in der Nordheide www.bbs-buchholz.de www.bbs-buchholz.de/internet/bildungsangebote/fachrichtungen/fachrichtungen.php#Informationsverarbeitung",
    "hs-offenburg.de": "Offenburg University of Applied Sciences",
    "drsneuwied.de": "David-Roentgen-Schule Neuwied",
    "bkgeldern.de": "Berufskolleg Geldern des Kreises Kleve",
    "schullogin.de": "Vitzthum Gymnasium Dresden",
    "uni-kl.de": "Universität Kaiserslautern",
    "rfh-campus.de": "Rheinische Fachhochschule Koeln",
    "ohmoor.de": "Gymnasium Ohmoor",
    "heinrich-kleyer-schule.de": "Heinrich-Kleyer-Schule Heinrich Kleyer School",
    "kbbz-dillingen.de": "Kaufmänisches Berufsbildungszentrum Dillingen KBBZ Dillingen",
    "csbme.de": "Carl-Severing-Berufskolleg für Metall- und Elektrotechnik",
    "fh-wiesbaden.de": "Fachhochschule Wiesbaden",
    "glh.de": "Gymnasium Lüneburger Heide",
    "uni-lueneburg.de": "Universität Lüneburg",
    "fhw-berlin.de": "Fachhochschule für Wirtschaft Berlin",
    "bracke-igs.de": "Wilhelm Bracke Gesamtschule",
    "bs-riedlingen.de": "Berufliche Schule Riedlingen",
    "bs19hh.de": "Berufliche Schule Farmsen 19, Hamburg",
    "fs.de": "Frankfurt School of Finance and Management",
    "Birklehof.de": "Schule Birklehof e.V. Hinterzarten",
    "uni-dortmund.de": "Universität Dortmund",
    "gywem.de": "Gymnasium Wesermünde",
    "wgmail.de": "Wolkenberg-Gymnasium Michendorf",
    "sdi-muenchen.de": "Sprachen und Dolmetscher Institut München",
    "ratsgymnasium-pe.de": "Ratsgymnasium Peine",
    "reutlingen-university.de": "Reutlingen University",
    "hfg-gmuend.de": "Fachhochschule Schwäbisch Gmünd, Hochschule für Gestaltung",
    "hs-owl.de": "Hochschule Ostwestfalen-Lippe",
    "bgbentheim.de": "Burg-Gymnasium Bad Bentheim",
    "hg-gladbeck.de": "Heisenberg Gymnasium",
    "gymnasium-hohenschwangau.de": "Staatliches Gymnasium mit Internat Hohenschwangau",
    "bbs-row.de": "BBS Rotenburg",
    "games-academy.de": "Games Academy",
    "kst-vechta.de": "Kolleg St. Thomas",
    "emg-haar.de": "Emg Haar",
    "fh-aachen.de": "Fachhochschule Aachen",
    "kath-fh-nord.de": "Katholische Fachhochschule Norddeutschland",
    "gymnasium-schmallenberg.de": "Gymnasium Schmallenberg",
    "hs-magdeburg.de": "Hochschule Magdeburg-Stendal (FH)",
    "asg-ehst.de": "Albert-Schweitzer Gymnasium Eisenhüttenstadt",
    "geomar.de": "GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel",
    "cbs-edu.de": "Cologne Business School",
    "igsquerum.de": "IGS Querum",
    "mls-marburg.de": "Martin-Luther Schule Marburg",
    "hawk-hhg.de": "HAWK Hochschule für angewandte Wissenschaft und Kunst Hildesheim Holzminden Göttingen",
    "ursulinenschule.de": "Ursulinenschule Fritzlar",
    "fhwue.de": "Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt",
    "bs1-bt.de": "Staatliche Berufsschule I Bayreuth Link to IT-course (3 years): https://www.bs1-bt.de/berufsschule/it Staff Email: firstname.surname@bs1-bt.de Students Emails differ from staff and are hosted via Microsoft, tha pattern is as follows: firstname.surename@berufsschulebt1.onmicrosoft.com",
    "mis-munich.de": "Munich International School",
    "fz-juelich.de": "Juelich Forschungzentrum",
    "asw-berufsakademie.de": "ASW – Berufsakademie Saarland e.V.",
    "vbs-lauterbach.de": "Vogelsbergschule Lauterbach",
    "maedchenrealschule-neumarkt.de": "Staatliche Mädchenrealschule",
    "hs-furtwangen.de": "Furtwangen University of Applied Sciences",
    "akad.de": "AKAD Hochschulen für Berufstätige, Fachhochschule Leipzig Hochschule für Berufstätige Rendsburg",
    "chf.de": "Institut Dr. Flad",
    "wbs-schulen.de": "WBS TRAINING Schulen",
    "i-u.de": "International University in Germany",
    "hawk.de": "HAWK Hochschule für angewandte Wissenschaft und Kunst",
    "gym-kothen.de": "Gymnasium Am Kothen",
    "ehs-dresden.de": "Evangelische Hochschule für Soziale Arbeit Dresden (FH)",
    "helmholtzschule.de": "Hermann-von-Helmholtz Gymnasium Potsdam",
    "konrad-zuse-schule.de": "Konrad-Zuse-Schule",
    "igs-os.de": "Integrierte Gesamtschule Osnabrück",
    "philtheol-augustin.de": "Philosophisch-Theologische Hochschule SVD Sankt Augustin",
    "hs-lausitz.de": "Hochschule Lausitz",
    "srhk.de": "Berlin School of Design and Communication",
    "tbk-solingen.de": "Technisches Berufskolleg Solingen",
    "ostendorfer.de": "Ostendorfer Gymnasium",
    "valckenburgschule.de": "Valckenburgschule Ulm",
    "kapellen-ms.de": "Kapellen-Mittelschule Augsburg",
    "smns-bw.de": "Staatliches Museum für Naturkunde Stuttgart",
    "mcg-berlin.de": "Marie Curie Gymnasium",
    "hector-seminar.de": "Hector Seminar Heidelberg, Karlsruhe, Mannheim, Pforzheim",
    "bs-erlangen.de": "Staatliche Berufsschule Erlangen",
    "staedelschule.de": "Hochschule für bildende Künste Frankfurt, Städelschule",
    "ph-freiburg.de": "Pädagogische Hochschule Freiburg",
    "tu-darmstadt.de": "Technische Universität Darmstadt",
    "ph-karlsruhe.de": "Pädagogische Hochschule Karlsruhe",
    "fh-bad-honnef.de": "Internationale Fachhochschule Bad Honnef",
    "tu-harburg.de": "Technische Universität Hamburg-Harburg",
    "kunstakademie-duesseldorf.de": "Kunstakademie Düsseldorf.",
    "gesamtschule-hardt.de": "gesamtschule-hardt.de",
    "iubh-dualesstudium.de": "IUBH Internationale Hochschule GmbH",
    "dhbw-karlsruhe.de": "Duale Hochschule Baden-Württemberg Karlsruhe",
    "kks-kiel.de": "Käthe-Kollwitz Gymnasium Kiel",
    "hu-berlin.de": "Humboldt Universität Berlin",
    "umwelt-campus.de": "Hochschule Trier, Umwelt-Campus Birkenfeld",
    "schiller-gymnasium-bautzen.de": "Schiller-Gymnasium Bautzen Schiller-Gymnasium Bautzen",
    "hs-fresenius.de": "Hochschule Fresenius",
    "bk-hennef.de": "Carl-Reuther-Berufskolleg des Rhein-Sieg-Kreises in Hennef",
    "wbstraining.de": "wbs training AG in Berlin,Germany Domain: https://www.wbstraining.de",
    "fh-rottenburg.de": "Fachhochschule Rottenburg, Hochschule für Forstwirtschaft",
    "kfhnw.de": "Katholische Fachhochschule Nordrhein-Westfalen",
    "evfh-berlin.de": "Evangelische Fachhochschule Berlin, Fachhochschule für Sozialarbeit und Sozialpädagogik",
    "efhlu.de": "Evangelische Fachhochschule Ludwigshafen Hochschule für Sozial- und Gesundheitswesen",
    "bfwob.de": "Berufsförderungswerk Oberhausen",
    "tu-muenchen.de": "Technical University of Munich",
    "berufskolleg-meschede.de": "Berufskolleg Meschede",
    "igs-kreyenbrueck.de": "Integrierte Gesamtschule Kreyenbrück",
    "fls-wiesbaden.de": "Friedrich-List-Schule Wiesbaden",
    "dhbw-vs.de": "Baden-Wuerttemberg Cooperative State University",
    "uni-koblenz.de": "University of Koblenz and Landau",
    "wb-fernstudium.de": "Wilhelm Büchner Hochschule Wilhelm Büchner Hochschule",
    "ovm-kassel.de": "Oskar-von-Miller-Schule Oskar-von-Miller-School",
    "rsplus-st-thomas.de": "St. Thomas Realschule plus",
    "syntax-institut.de": "Syntax Institut",
    "htwm.de": "Hochschule Mittweida (FH)",
    "uni-duisburg-essen.de": "Universität Duisburg-Essen",
    "hs-mainz.de": "Hochschule Mainz - University of Applied Sciences",
    "gwdg.de": "Georg-August-Universtät Göttingen Georg-August-University Goettingen",
    "fh-telekom-leipzig.de": "Deutsche Telekom Fachhochschule Leipzig",
    "th-bingen.de": "Technische Hochschule Bingen University of Applied Sciences",
    "avg-wesel.de": "Andreas-Vesalius-Gymnasium",
    "hfph.de": "Hochschule für Philosophie, Muenchen",
    "dbg-ratingen.de": "Dietrich-Bonhoeffer-Gymnasium Ratingen",
    "mediadesign.de": "Mediadesign Hochschule",
    "uni-rostock.de": "Universität Rostock",
    "kwr-hannover.de": "Kaiser- Wilhelm und Ratsgymnasium Hannover",
    "wuemmeschule.de": "Wümmeschule Ottersberg",
    "eggk.de": "Evangelisches Gymnasium zum Grauen Kloster",
    "hs-weingarten.de": "University of Applied Sciences Ravensburg-Weingarten",
    "geporta.de": "Gesamtschule Porta Westfalica",
    "fs-students.de": "Frankfurt School of Finance & Management",
    "gymnasium-frechen.de": "Gymnasium Frechen",
    "fhs-mannheim.de": "Fachhochschule Mannheim, Hochschule für Sozialwesen",
    "onbtineuss.de": "Berufskolleg für Technik und Informatik Neuss BTI Neuss",
    "berufskolleg-beckum.de": "Berufskolleg Beckum des Kreises Warendorf Europaschule",
    "zgk-konstanz.de": "Zeppelin-Gewerbeschule Konstanz",
    "hs-bremen.de": "Hochschule Bremen",
    "hanseuni.de": "Private Hanseuniversität",
    "albbw.de": "Annedore-Leber-Berufsbildungswerk Berlin",
    "fh-sm.de": "Fachhochschule Schmalkalden",
    "barnim-gym.de": "Barnimgymnasium Berlin-Lichtenberg",
    "iserv-trg-oha.de": "Tilman-Riemenschneider-Gymnasium Osterode am Harz",
    "cmb-gt.de": "Carl-Miele-Berufskolleg für Technik",
    "ue-germany.de": "University of Applied Sciences Europe (Campus Hamburg) University of Applied Sciences Europe (Campus Hamburg)",
    "osrw.de": "Oberschule Rauschwalde Görlitz",
    "hs-gesundheit.de": "Hochschule für Gesundheit",
    "hs-rm.de": "Rheinmain University of Applied Sciences",
    "saglh.de": "Sant Antonius Gymnasium Sant Antonius Gymnasium",
    "sts-bahrenfeld.de": "Esther Bejerano Schule Stadtteilschule Bahrenfeld",
    "zu.de": "Zeppelin University",
    "jakob-brucker-gymnasium.de": "Jakob-Brucker-Gymnasium, Kaufbeuren",
    "fh-muenchen.de": "Fachhochschule München",
    "hs-ulm.de": "University of Applied Sciences Ulm",
    "lwl-vvs.de": "Von-Vinke-Schule Soest",
    "khm.de": "Academy of Media Arts, Cologne",
    "phwt.de": "Private Hochschule fur Wirtschaft und Technick",
    "ph-ludwigsburg.de": "Pädagogische Hochschule Ludwigsburg",
    "ba-eisenach.de": "Berufsakademie Eisenach",
    "pfh.de": "Private Hochschule Göttingen",
    "b-tu.de": "Brandenburg University of Technology Cottbus–Senftenberg",
    "popakademie.de": "Popakademie Baden-Württemberg",
    "gywa.de": "Gymnasium Waldstraße, Germany https://gywa.de/",
    "bbs-lingen-wirtschaft.de": "BBS Wirtschaft Lingen BBS Lingen economy",
    "berlin.de": "Fachhochschule für Verwaltung und Rechtspflege Berlin",
    "gs-wt.de": "Gewerbliche Schulen Waldshut",
    "fh-hof.de": "Fachhochschule Hof",
    "schule-sh.de": "Schleswig-Holstein Schools, Germany",
    "sis-fellbach.de": "Swiss International School",
    "rbs-ulm.de": "Robert-Bosch-Schule Ulm",
    "ers-hameln.de": "Eugen-Reintjes-Schule Hameln",
    "th-owl.de": "Technische Hochschule Ostwestfalen-Lippe OWL University of Applied Sciences",
    "technik-emden.de": "Hochschule Emden-Leer",
    "bbs2wob.de": "Berufsbildende Schulen 2 Wolfsburg",
    "hs-mittweida.de": "University of Applied Sciences Mittweida",
    "uni-osnabrueck.de": "Universität Osnabrück",
    "efh-darmstadt.de": "Evangelische Fachhochschule Darmstadt",
    "dhbw-mosbach.de": "Duale Hochschule Baden-Württemberg, Mosbach",
    "bsz-waldkirch.de": "Berufliches Schulzentrum Waldkirch",
    "sportschule-potsdam.de": "Sportschule Potsdam",
    "hgo-ol.de": "Herbartgymnasium Oldenburg",
    "hsba.de": "HSBA Hamburg School of Business Administration (old accounts)",
    "mseu.de": "Marienschule Euskirchen",
    "selk.de": "Lutherische Theologische Hochschule Oberursel",
    "carl-miele-berufskolleg.de": "Carl-Miele-Berufskolleg für Technik",
    "fh-trier.de": "Fachhochschule Trier, Hochschule für Technik, Wirtschaft und Gestaltung",
    "hgw-iserv.de": "Hölty-Gymnasium Wunstorf",
    "aeg-boeblingen.de": "Albert-Einstein-Gymnasium Böblingen",
    "fh-duesseldorf.de": "Hochschule Düsseldorf",
    "dalberg-gymnasium.de": "Karl-Theodor-v.-Dalberg-Gymnasium",
    "ess-liborius.de": "Liborius Gymnasium Dessau",
    "hs-kl.de": "Hochschule Kaiserslautern University of Applied Sciences",
    "pth-muenster.de": "Philosophisch-Theologische Hochschule Münster",
    "ferdinand-braun-schule.de": "Ferdinand-Braun-Schule",
    "jkg-ibb.de": "Johannes-Kepler-Gymnasium Ibbenbüren",
    "genoapps.de": "Genokolleg Münster",
    "ludwig-geissler-schule.de": "Ludwig-Geißler-Schule",
    "jhgcloud.de": "JosephHaydenGymnasium",
    "freie-schule-anne-sophie.de": "Freie Schule Anne-Sophie",
    "victoria-hochschule.de": "Victoria | Internationale Hochschule Victoria | International University of Applied Sciences",
    "hs-anhalt.de": "Hochschule Anhalt (FH), Hochschule für angewandte Wissenschaften",
    "gesamtschule-stolberg.de": "Staedtische Gesamtschule Stolberg https://gesamtschule-stolberg.de https://gesamtschule-stolberg.de/wp-content/uploads/2018/09/Schulprogramm017-09-19.pdf",
    "feintechnikschule.de": "Staatliche Feintechnikschule mit Technischem Gymnasium Schwenningen",
    "fhdw.de": "Fachhochschule der Wirtschaft",
    "bbssoltau.de": "Berufsbildende Schulen Soltau",
    "bbs1-lg.de": "Berufsbildenden Schulen I Lüneburg",
    "stresemanngymnasium.de": "Gustav Stresemann Gymnasium",
    "nta-isny.de": "Naturwissenschaftlich technische Akademie Isny - Fachhochschule & Berufskollegs Prof. Dr. Grübler GmbH Scientific and technical academy Isny - University of Applied Science and Vocational Colleges, Prof. Dr. Gruebler ltd.",
    "bccn-berlin.de": "BERNSTEIN CENTER FOR COMPUTATIONAL NEUROSCIENCE, BERLIN",
    "bbs-montabaur.de": "BBS Montabaur",
    "uni-mannheim.de": "Universität Mannheim",
    "gsp-ploen.de": "Gymnasium Schloss Plön",
    "hs-nb.de": "Hochschule Neubrandenburg",
    "doz-provadis-hochschule.de": "Provadis School of International Management & Technology AG",
    "eufh-mail.de": "Europäische Fachhochschule",
    "gym-stolz.de": "Gymnasium Stolzenau",
    "bbs1-kl.de": "Berufsbildenden Schulen I Kaiserslautern",
    "obs-hilter.de": "Oberschule Hilter",
    "anna-schmidt-schule.de": "Anna Schmidt Schule",
    "health-and-medical-university.de": "Health and Medical University",
    "mws-mainz.de": "Maria Ward-Schule Mainz",
    "fvs-sus.de": "FvS Minden - Freiherr-vom-Stein-Berufskolleg Minden",
    "igs-goettingen.de": "Georg-Christoph-Lichtenberg-Gesamtschule Göttingen-Geismar",
    "folkwang-uni.de": "Folkwang Universtität der Künste Folkwang University of the arts",
    "hsu-hh.de": "Helmut-Schmidt-Universität - Universität der Bundeswehr Hamburg Helmut-Schmidt-University Hamburg (Germany)",
    "gymnasium-himmelsthuer.de": "Gymnasium Himmelsthür",
    "stiftsgymnasium.de": "Stiftsgymnasium Sindelfingen",
    "sus-am-bktm.de": "Berufskolleg Platz der Republik für Technik und Medien",
    "gymnasium-babelsberg.de": "Bertha von Suttner Gymnasium Babelsberg",
    "rbbk-dortmund.de": "Robert-Bosch-Berufskolleg",
    "gymnasium-mariengarden.de": "Gymnasium Mariengarden",
    "th-ab.de": "Technische Hochschule Aschaffenburg University of applied sciences Aschaffenburg",
    "bso-hef.de": "Berufliche Schulen Bad Hersfeld",
    "fh-kiel.de": "Fachhochschule Kiel",
    "cdtm.de": "Center for Digital Technology and Management",
    "ohs-bensberg.de": "Otto-Hahn-Gymnasium Bergisch Gladbach - Bensberg",
    "jsg-karlstadt.de": "Johann-Schöner-Gymnasium Karlstadt",
    "rss-witten.de": "Rudolf-Steiner-Schule Witten Rudolf-Steiner-School Witten",
    "srh.de": "SRH Berufliche Rehabilitation GmbH",
    "pthv.de": "Philosophisch-Theologische Hochschule Vallendar der Gesellschaft des Katholischen Apostolates (Pallottiner)",
    "julianum.de": "Gymnasium Julianum",
    "fichtenberg-oberschule.de": "Fichtenberg-Oberschule",
    "dhbw-stuttgart.de": "Duale Hochschule Baden-Württemberg Stuttgart",
    "domgymnasium-verden.de": "Domgymnasium Verden",
    "nordakademie.de": "Nordakademie, Staatlich anerkannte private Fachhochschule mit dualen Studiengängen",
    "uni-bamberg.de": "Otto-Friedrich Universität Bamberg",
    "zgs-konstanz.de": "Zeppelin Gewerbeschule Konstanz",
    "hgbp.de": "Humboldt Gymnasium Bad Pyrmont",
    "bk-deutz.de": "Berufskolleg Deutzer Freiheit",
    "kmg-fn.de": "Karl-Maybach-Gymnasium Friedrichshafen",
    "kfh-mainz.de": "Katholische Fachhochschule Mainz",
    "iubh-fernstudium.de": "Internationale Hochschule Bad Honnef · Bonn",
    "edv-schulen-wiesau.de": "Staatliche EDV-Schulen Wiesau Berufliches Schulzentrum Wiesau",
    "hs-harz.de": "Hochschule Harz, Hochschule für angewandte Wissenschaften (FH)",
    "tu-ilmenau.de": "Technische Universität Ilmenau",
    "wbgym.de": "Weinberg Gymnasium Kleinmachnow",
    "wwgsk.de": "Wirtschaftswissenschaftliches Gymnasium und Saarland-Kolleg",
    "lazi-akademie.de": "Lazi Akademie is an Academy for Media Design in Esslingen, Germany Homepage: https://www.lazi-akademie.de/ 3 years education: https://www.lazi-akademie.de/ausbildung/grafik-kommunikationsdesign/ https://www.lazi-akademie.de/master-of-arts/ Domain for repository: lazi-akademie.de",
    "htwsaar.de": "Hochschule für Technik und Wirtschaft des Saarlandes",
    "bs1in.de": "Staatliche Berufsschule I Ingolstadt",
    "jules-verne-campus.de": "Jules Verne Campus",
    "lebk247.de": "Ludwig-Erhard-Berufskolleg Muenster",
    "hoenne-berufskolleg.de": "Hoenne-Berufskolleg",
    "hochschule-regensburg.de": "Hochschule Regensburg",
    "dbuas.de": "Digital Business University of Applied Sciences",
    "gms-da.de": "Georg Mueller Schule Darmstadt",
    "mdg-hamburg.de": "Marion Dönhoff Gymnasium",
    "merz-akademie.de": "Merz Akademie, Hochschule für Gestaltung Stuttgart",
    "gustav-heinemann-oberschule.de": "Gustav-Heinemann-Oberschule",
    "karlkuebelschule.de": "Karl Kübel Schule",
    "louisenlund.de": "Stiftung Louisenlund Louisenlund Foundation",
    "pmhs.de": "Philipp-Matthäus-Hahn-Schule Nürtingen",
    "fh-koblenz.de": "Fachhochschule Koblenz",
    "bk-h.de": "Berufskolleg Hattingen",
    "mpg-trier.de": "Max-Planck-Gymnasium Trier",
    "feg-sandhausen.de": "Friedrich-Ebert-Gymnasium Sandhausen",
    "dhfpg.de": "Deutsche Hochschule für Prävention und Gesundheitsmanagement",
    "dacs-bund.de": "Hochschule des Bundes für öffentliche Verwaltung",
    "aeg-nb.de": "Albert-Einstein-Gymnasium Neubrandenburg",
    "lg-bs.de": "Lessinggymnasium Braunschweig",
    "hzdr.de": "Helmholtz-Zentrum Dresden-Rossendorf",
    "hs-fulda.de": "Hochschule Fulda",
    "hs-albsig.de": "Hochschule Albstadt-Sigmaringen",
    "fern-fh.de": "Fern-Fachhochschule Hamburg",
    "deutschehochschule.de": "Deutsche Hochschule für angewandte Wissenschaften (DHAW) German University of Applied Sciences",
    "ferdinand-steinbeis-institut.de": "Ferdinand Steinbeis Institute, Stuttgart Steinbeis University, Berlin Bildungscampus, Heilbronn",
    "waldorf-augsburg.de": "Freie Waldorfschule Augsburg",
    "fh-stralsund.de": "Fachhochschule Stralsund",
    "zsl-rss.de": "Zentrum für Schulqualität und Lehrerbildung Baden-Württemberg, Regionalstelle Stuttgart",
    "bs-hassfurt.de": "Heinrich-Thein-Schule Staatliches Berufliches Schulzentrum Haßfurt",
    "bs1-landshut.de": "Staatliche Berufsschule 1 Landshut mit Berufsfachschule für Informatik Public Vocational School 1 Landshut with Vocational School for Informatics",
    "szh-ahrensburg.de": "Gemeinschafts Schule am Heimgarten",
    "uni-freiburg.de": "Albert-Ludwigs-Universität Freiburg",
    "bfw-koblenz.de": "CJD Berufsförderungswerk Koblenz Gemeinnützige GmbH",
    "markdorf-robotics.de": "Gymnasium im Bildungszentrum Markdorf - Roboter AG",
    "hfb.de": "Hochschule für Bankwirtschaft (HfB), Private Fachhochschule der Bankakademie",
    "cjd-bs.de": "CJD Jugenddorf-Christophorusschule Braunschweig",
    "sgy-dt.de": "Stadtgymnasium Detmold",
    "fh-heidelberg.de": "Fachhochschule Heidelberg",
    "gsso.de": "Grafenbergschule Schorndorf",
    "lwl-bz-soest.de": "LWL Berufskolleg Soest",
    "uni-muenchen.de": "Ludwig-Maximilians-Universität München",
    "ba-rm.de": "Berufsakademie Rhein Main",
    "sz-haltern.de": "Joseph-König-Gymnasium Haltern am See Alexander-Lebenstein-Realschule Haltern am See at Schulzentrum Haltern am See",
    "dhfpg-bsa.de": "Deutsche Hochschule für Prävention und Gesundheitsmanagement",
    "mtgmuenchen.de": "Staatliches Maria-Theresia-Gymnasium München",
    "element-i-schule.de": "Freie element-i Gemeinschaftsschule im Bildungshaus Karlsruhe",
    "thws.de": "Technische Hochschule Würzburg-Schweinfurt",
    "rs-unterpfaffenhofen.de": "Staatliche Realschule Unterpfaffenhofen",
    "bbw-fi.de": "SFZ Förderzentrum gGmbH (Berufsbildungswerk Chemnitz)",
    "tbs1.de": "Technische Berufliche Schule 1 - Bochum",
    "krbor.de": "Berufskollegs des Kreises Borken",
    "hfbk-hamburg.de": "Hochschule für bildende Künste Hamburg",
    "asg-huerth.de": "Albert-Schweitzer-Gymnasium Hürth",
    "wwu.de": "University of Münster",
    "fh-koeln.de": "Technische Hochschule Köln",
    "berufskolleg-kleve.de": "Berufskolleg des Kreises Kleve in Kleve",
    "gymbruck.de": "Gymnasium Bruckmuehl",
    "lore-lorentz-schule.de": "Lore Lorentz Schule",
    "sartre-gymnasium.de": "Sartre-Gymnasium Berlin",
    "aegmail.de": "Albert-Einstein-Gymnasium Duisburg-Rumeln",
    "hft-stuttgart.de": "Stuttgart University of Applied Sciences",
    "hochschule-stralsund.de": "Fachhochschule Stralsund",
    "eba-muenchen.de": "Europäische Betriebswirtschafts-Akademie",
    "fh-nordhausen.de": "Fachhochschule Nordhausen",
    "europa-uni.de": "",
    "tu-berlin.de": "Technische Universität Berlin",
    "wvs-ffm.de": "Werner-von-Siemens-Schule",
    "gym-meiendorf.de": "Name: Gymnasium Meiendorf Website: https://www.gymei.de/ E-Mail Proof: https://www.gymei.de/impressum/",
    "thk-optec.de": "Institute of Optical Technologies at Cologne University of Applied Sciences, Germany",
    "fh-kl.de": "Fachhochschule Kaiserslautern",
    "paderborn.de": "Theologische Fakultät Paderborn",
    "bszh.de": "Staatliches Berufsschulzentrum Hermsdorf",
    "fmsg-speyer.de": "Friedrich-Magnus-Schwerd Gymnasium Speyer",
    "gym-schiff.de": "Gymnasium Schifferstadt im Paul-von-Denis-Schulzentrum",
    "fh-lippe.de": "Fachhochschule Lippe",
    "fes-es.de": "Friedrich-Ebert Schule Esslingen",
    "ess-erfurt.de": "Edith Stein Schule Erfurt Edith Stein School Erfurt",
    "bkgut.de": "Berufskolleg für Gestaltung und Technik Aachen Vocational college for design and engineering, Aachen Teacher accounts",
    "dhbw-heidenheim.de": "Duale Hochschule Baden-Württemberg, Heidenheim",
    "fh-bochum.de": "Fachhochschule Bochum",
    "igs-winsen.de": "IGS Winsen Roydorf",
    "wara.de": "Walther-Rathenau Gewerbeschule Freiburg",
    "tfh-bochum.de": "Technische Fachhochschule Georg Agricola für Rohstoff, Energie und, Umwelt zu Bochum",
    "dbb-detmold.de": "Dietrich-Bonhoeffer-Berufskolleg des Kreises Lippe in Detmold (dbb)",
    "uni-goettingen.de": "Georg-August Universität Göttingen",
    "ths-berlin.de": "Theodor-Haubach-Schule",
    "haw-ingolstadt.de": "Ingolstadt University of Applied Sciences",
    "ovgu.de": "Otto von Guericke University of Magdeburg",
    "hs-bochum.de": "Hochschule Bochum",
    "leogos.de": "Leononore Goldschmidt Schule",
    "filmuniversitaet.de": "Filmuniversität Babelsberg-Potsdam",
    "fh-konstanz.de": "Fachhochschule Konstanz, Hochschule für Technik, Wirtschaft und Gestaltung",
    "gd-serv.de": "Gymnasium Damme",
    "unibw.de": "Universität der Bundeswehr München www.unibw.de",
    "bs-gelnhausen.de": "Berufliche Schulen des Main-Kinzig-Kreises in Gelnhausen (Teacher accounts)",
    "srh-berlin.de": "SRH University of Applied Sciences",
    "buhmann.de": "Dr. Buhmann Schule & Akademie Hannover Dr. Buhmann School & Academy Hanover",
    "bws-hofheim.de": "Brühlwiesenschule Hofheim",
    "fu-berlin.de": "Freie Universität Berlin",
    "fh-ottersberg.de": "Freie Kunst-Studienstätte Ottersberg",
    "kinzig-schule.de": "Berufliches Schulzentrum des Main-Kinzig-Kreises in Schlüchtern",
    "myhsba.de": "HSBA Hamburg School of Business Administration",
    "maxe-del.de": "Max-Planck-Gymnasium, Delmenhorst mpg Delmenhorst",
    "fosbos-neumarkt.de": "Maximilian Kolbe (Fachober- & Berufsober-) Schule Neumarkt",
    "jade-hs.de": "Jade Hochschule Wilhelms/Oldenburg/Elsfleth",
    "bildung-unna.de": "Hellweg Berufskolleg Unna",
    "its-stuttgart.de": "it.schule Stuttgart",
    "uni-kassel.de": "Universität Kassel",
    "uni-weimar.de": "Bauhaus-Universität Weimar",
    "efh-bochum.de": "Evangelische Fachhochschule Rheinland-Westfalen-Lippe",
    "mm-bbs.de": "multi media BBS Hannover",
    "bbs-ww.de": "BBS Westerburg HBFI Westerburg",
    "h-da.de": "Hochschule Darmstadt University of Applied Sciences",
    "abs-it-kiel.de": "ABS-IT UG (haftungsbeschränkt) Geschäftsführer Paul Klein M.A. Werftstraße 193 24143 Kiel Email: info@abs-it-kiel.de Domain: https://www.abs-it-kiel.de",
    "fh-frankfurt.de": "Fachhochschule Frankfurt am Main",
    "schueler-bsd.de": "Staatliche Berufsschule Dachau Nikolaus-Lehner-Schule",
    "bksuedstadt.de": "Berufskolleg Südstadt",
    "th-luebeck.de": "TH Lübeck",
    "uni-greifswald.de": "Ernst-Moritz-Arndt Universität Greifswald",
    "euv-frankfurt-o.de": "Europa-Universität Viadrina Frankfurt (Oder)",
    "jws-rv.de": "Josef-Wilhelm-Schule Ravensburg",
    "uni-magdeburg.de": "Otto-von-Guericke Universität Magdeburg",
    "bkhaspel.de": "Berufskolleg Am Haspel",
    "uni-flensburg.de": "Universität Flensburg",
    "neponet.de": "Gymnasium Nepomucenum Coesfeld",
    "bfw-hamburg.de": "Berufsförderungswerk Hamburg Bfw Hamburg",
    "mpg-bb.de": "Max-Planck-Gymnasium Böblingen",
    "joseph-koenig-gymnasium.de": "Joseph-Koenig-Gymnasium Haltern am See",
    "sadds.de": "Schule an der Donauschleife",
    "fh-dortmund.de": "Fachhochschule Dortmund",
    "berufskolleg-technik.de": "Berufskolleg Technik des Kreises Siegen-Wittgenstein",
    "hs-flensburg.de": "Hochschule Flensburg",
    "gymolching.de": "Gymnasium Olching",
    "fh-zwickau.de": "Westsächsische Hochschule Zwickau",
    "bbsandernach.de": "BBS Andernach August-Horch-Schule",
    "aibgym.de": "Gymnasium Bad Aibling",
    "lio-darmstadt.de": "Justus-Liebig-Schule Darmstadt Justus-Liebig school Darmstadt, Germany",
    "friedrich-ebert-gymnasium.de": "Friedrich Ebert Gymnasium",
    "rsu-germering.de": "Staatliche Realschule Unterpfaffenhofen",
    "thm.de": "University of Applied Sciences Giessen-Friedberg",
    "filmakademie.de": "Filmakademie Baden-Württemberg",
    "hbbk-office.de": "Hans-Böckler-Berufskolleg, Münster (hbbk-muenster.de)",
    "iservigs-embsen.de": "IGS Embsen",
    "fh-regensburg.de": "Fachhochschule Regensburg",
    "igssolms-ldk.de": "Integrierte Gesamtschule Solms",
    "ppc-schule.de": "Peter-Paul-Cahensly Schule",
    "bbstghs.de": "﻿Berufliches Gymnasium Technik Bad Kreuznach",
    "dhv-speyer.de": "Deutsche Hochschule für Verwaltungswissenschaften Speyer",
    "uni-leipzig.de": "Universität Leipzig",
    "hlg-do-edu.de": "Helene Lange Gymnasium Dortmund",
    "hochschule-bc.de": "Hochschule Biberach Hochschule Biberach (Biberach University of Applied Sciences)",
    "thi.de": "Technische Hochschule Ingolstadt",
    "kbs-nordhorn.de": "Kaufmännische Berufsbildende Schulen Nordhorn (KBS)",
    "filderbenden.de": "Gymnasium in den Filder Benden",
    "neg-velbert.de": "Nikolaus-Ehlen-Gymnasium",
    "julius-wegeler-schule.de": "Julius-Wegeler-Schule Koblenz",
    "bbstghs365.de": "﻿Berufliches Gymnasium Technik Bad Kreuznach",
    "bs1-kempten.de": "Staatliche Berufsschule I Kempten",
    "beuth-hochschule.de": "Beuth Hochschule für Technik Berlin",
    "fh-niederrhein.de": "Fachhochschule Niederrhein",
    "fh-osnabrueck.de": "Fachhochschule Osnabrück",
    "hs-sm.de": "Hochschule Schmalkalden",
    "list-gymnasium.de": "Friedrich List Gymnasium Reutlingen Friedrich List High School Reutlingen",
    "lmgrhl.de": "Lise-Meitner-Gesamtschule",
    "fh-giessen.de": "Fachhochschule Gießen-Friedberg",
    "itbspa.de": "Karl-Peter-Obermaier Schule Passau",
    "gsz-bl.de": "Philipp-Matthäus-Hahn-Schule – Gewerbliches Schulzentrum Balingen",
    "hkdm.de": "Hochschule für Kunst, Design und populäre Musik Freiburg",
    "ammersee-gymnasium.de": "Ammersee-Gymnasium",
    "bk-opladen.de": "Berufskolleg Opladen",
    "thga.de": "Technische Hochschule Georg Agricola University of Applied Sciences Georg Agricola",
    "anno-gymnasium.de": "Städtisches Anno-Gymnasium Siegburg",
    "schueler-bkgut.de": "Berufskolleg für Gestaltung und Technik Aachen Vocational college for design and engineering, Aachen Student accounts",
    "ku.de": "Katholische Universität Eichstätt",
    "fom.de": "Fachhochschule für Oekonomie und Management (FOM)",
    "genth-schule.de": "Kooperative Gesamtschule des Main-Kinzig-Kreises",
    "uni-bremen.de": "Universität Bremen",
    "siegtal-gymnasium.de": "Siegtal-Gymnasium Eitorf",
    "firstwald.de": "Evangelisches Firstwald Gymnasium Mössingen",
    "fh-Kempten.de": "Fachhochschule Kempten, Hochschule für Technik und Wirtschaft",
    "haw-landshut.de": "Landshut University of Applied Sciences",
    "bbw-rki-berlin.de": "Rotkreuz-Institut Berufsbildungswerk Homepage:https://www.rkibbw.de/ IT-Course example: https://www.rkibbw.de/angebote/berufsausbildung/fachinformatiker-anwendungsentwicklung.html",
    "ulricianum-aurich.de": "Gymnasium Ulricianum Aurich",
    "thh-friedensau.de": "Theologische Hochschule Friedensau",
    "rwu.de": "RWU Hochschule Ravensburg-Weingarten University of Applied Sciences",
    "uni-bayreuth.de": "Universität Bayreuth",
    "tek-up.de": "TEK-UP University TEK-UP University",
    "hs-pforzheim.de": "Hochschule Pforzheim für Gestaltung, Technik und Wirtschaft",
    "hss-wiesloch.de": "Hubert-Sternberg-Schule Wiesloch",
    "uni-koblenz-landau.de": "Universität Koblenz-Landau",
    "fh-lausitz.de": "Fachhochschule Lausitz",
    "privatgymnasium-weinheim.de": "Privatgymnasium Weinheim",
    "bbzsm.de": "Berufsbildungszentrum Schmalkalden",
    "fh-furtwangen.de": "Fachhochschule Furtwangen, Hochschule für Technik und Wirtschaft",
    "mh-freiburg.de": "Hochschule für Musik Freiburg",
    "rptu.de": "Rheinland-Pfälzische Technische Universität Kaiserslautern-Landau University of Kaiserslautern-Landau",
    "gghi.de": "Goethegymnasium Hildesheim",
    "bk-berliner-platz.de": "Berufskolleg Berliner Platz",
    "hebk.de": "Hermann-Emanuel-Berufskolleg",
    "fos-karlsfeld.de": "Fos Karlsfeld",
    "fh-landshut.de": "Fachhochschule Landshut, Hochschule für Wirtschaft - Sozialwesen - Technik",
    "carl-orff-gym.de": "Carl-Orff-Gymnasium Unterschleißheim",
    "bs-wangen.de": "Berufliches Schulzentrum Wangen",
    "bbs1-gifhorn.de": "BBS1 Gifhorn Berufsbildene Schule 1 Gifhorn",
    "mesk.de": "Max-Eyth-Schule Kirchheim",
    "iserv-schiller-schule.de": "Schiller-Schule Bochum",
    "bbs-stadthagen.de": "Berufsbildende Schule Stadthagen vocational schools Stadthagen",
    "oegym.de": "Ökumenisches Gymnasium zu Bremen",
    "hbg-troisdorf.de": "Heinrich-Böll-Gymnasium",
    "drsschueler.de": "David-Roentgen-Schule Neuwied",
    "fh-reutlingen.de": "Fachhochschule Reutlingen, Hochschule für Technik und Wirtschaft",
    "hs-esslingen.de": "Hochschule Esslingen",
    "fg-kassel.de": "Friedrichsgymnasium Kassel",
    "eichendorff-gymnasium.de": "Eichendorff Gymnasium Ettlingen",
    "kerschensteinerschule.de": "Kerschensteinerschule.de",
    "berufsschule-dachau.de": "Staatliche Berufsschule Dachau Nikolaus-Lehner-Schule",
    "gymger.de": "Gymnasium Geretsried",
    "sbsz-jena.de": "Staatliches Berufsbildendes Schulzentrum Jena-Göschwitz State vocational school center Jena-Göschwitz SBSZ Jena-Göschwitz https://www.sbsz-jena.de/",
    "goetheschule-ldk.de": "Goetheschule Wetzlar",
    "liebigschule-giessen.de": "Liebigschule Giessen",
    "bht-berlin.de": "Berliner Hochschule für Technik",
    "bbs-holzminden.de": "Georg-von-Langen-Schule Georg-von-Langen School",
    "diesterweg-gymnasium.de": "Diesterweg Gymnasium",
    "uni-stuttgart.de": "Universität Stuttgart",
    "cmb-portal.de": "Carl-Miele-Berufskolleg des Kreises Gütersloh",
    "obsbs.de": "Otto-Bennemann-Schule, Berufsbildende Schulen Wirtschaft und Verwaltung",
    "law-school.de": "Bucerius Law School gGmbH",
    "mhmk.de": "Hochschule Macromedia University of Applied Sciences",
    "uol.de": "Carl von Ossietzky Universität Oldenburg https://uol.de/en https://uol.de/en/course-of-study/computing-science-subject-bachelor-133 https://uol.de/en/it-services/services/user-account-at-the-university/user-account-for-university-members",
    "wvss-hildesheim.de": "Werner-von-Siemens-Schule Hildesheim",
    "franz-oberthuer-schule.de": "Franz Oberthür Schule",
    "uni-siegen.de": "Universität Siegen",
    "sembska.de": "Seminar Berufliche Schulen Karlsruhe",
    "hsw-hameln.de": "Hochschule Weserbergland",
    "dhge.de": "Duale Hochschule Gera Eisenach Gera Eisenach Cooperative State University",
    "khsa.de": "Katholische Hochschule für Soziale Arbeit Saarbrücken",
    "tu-dresden.de": "Technische Universität Dresden",
    "uni-koeln.de": "Universität Köln",
    "best-sabel.de": "BEST-Sabel Designschule Berlin Germany",
    "pertha.de": "Pertha Universität Pertha University",
    "mercator-berufskolleg.de": "",
    "businessschool-berlin.de": "BSP Business & Law School Berlin",
    "uni-tuebingen.de": "Eberhard-Karls-Universität Tübingen",
    "mcleon.de": "McLeon International Institute of Technology and Business",
    "fh-westkueste.de": "Fachhochschule Westküste, Hochschule für Wirtschaft und Technik",
    "bib.de": "Fachhochschule für die Wirtschaft",
    "fra-uas.de": "Frankfurt University of Applied Sciences",
    "gs-bk.de": "Gewerbliche Schule Backnang",
    "fh-ingolstadt.de": "Fachhochschule Ingolstadt",
    "io-warnemuende.de": "Leibniz Insitut für Ostseeforschung Warnemünde (IOW) Leibniz Institute for Baltic Sea Research Warnemünde (IOW)",
    "louis-leitz-schule.de": "Louis Leitz Schule",
    "uni-hildesheim.de": "Universität Hildesheim",
    "bs-elmshorn.de": "Berufliche Schule des Kreises Pinneberg in Elmshorn, Europaschule http://www.bs-elmshorn.de",
    "mytum.de": "Technical University of Munich",
    "mpia.de": "International Max Planck Research School for Astronomy and Cosmic Physics at the University of Heidelberg",
    "ebs-iserv.de": "ELSA-BRÄNDSTRÖM-SCHULE",
    "tu-bs.de": "Technische Universität Carolo-Wilhelmina zu Braunschweig",
    "hssfds.de": "Heinrich-Schickhardt-Schule",
    "riemenschneider-gymnasium.de": "Riemenschneider Gymnasium Würzburg",
    "haw-hamburg.de": "Hamburg University of Applied Sciences",
    "semperschulen.de": "Semper Schulen",
    "mhn.de": "Hochschule für Politik (HFP)",
    "reuchlin-gymnasium.de": "Reuchlin-Gymnasium Pforzheim",
    "lsbkmi.de": "Leo-Sympher-Berufskolleg",
    "cbs-heidelberg.de": "Carl-Bosch-Schule Heidelberg",
    "hoev-rlp.de": "Hochschule für öffentliche Verwaltung Rheinland-Pfalz",
    "h-ab.de": "Hochschule Aschaffenburg",
    "fh-augsburg.de": "Fachhochschule Augsburg",
    "weg-schwabach.de": "Wolfram-von-Eschenbach-Gymnasium Schwabach",
    "ph-gmuend.de": "Pädagogische Hochschule Schwäbisch Gmünd",
    "schuldorf.de": "Schuldorf Bergstraße, Seeheim-Jugenheim",
    "fes365-pfungstadt.de": "Friedrich-Ebert-Schule, Pfungstadt http://www.fes-pfungstadt.de",
    "ba-glauchau.de": "Staatliche Studienakademie Glauchau",
    "charite.de": "﻿Charité - Universitätsmedizin Berlin",
    "dbb-lippe.de": "Dietrich-Bonhoeffer-Berufskolleg des Kreises Lippe in Detmold (dbb)",
    "fh-merseburg.de": "Fachhochschule Merseburg",
    "dh-karlsruhe.de": "DHBW-Karlsruhe",
    "fh-wolfenbuettel.de": "Fachhochschule Braunschweig/Wolfenbüttel",
    "rks-linz.de": "Robert-Koch-Schule",
    "hfmt-koeln.de": "Hochschule für Musik und Tanz Köln",
    "hnbk.de": "Heinz-Nixdorf-Berufskolleg Essen",
    "stiftkeppel.de": "Gymnasium Stift Keppel",
    "uni-luebeck.de": "University of Lübeck",
    "students-hnbk.de": "Heinz-Nixdorf Berufskolleg",
    "lgs-di.de": "Landrat-Gruber-Schule",
    "uni-oldenburg.de": "Carl von Ossietzky Universität Oldenburg",
    "max-weber-schule.de": "Max-Weber-Schule Freiburg im Breisgau",
    "neue-schule-magdeburg.de": "Neue Schule Magdeburg",
    "bs-schramberg.de": "Berufliche Schulen Schramberg",
    "hfk-bremen.de": "Hochschule für Künste Bremen",
    "hs-emden-leer.de": "Hochschule Emden / Leer",
    "tu-clausthal.de": "Technische Universität Clausthal",
    "w-hs.de": "Westfalia University of Applied Sciences",
    "gg-lin.de": "Gymnasium Georgianum Lingen Georgianum High School Lingen",
    "leibniz-gymnasium-essen.de": "Leibniz-Gymnasium Essen",
    "isr-school.de": "International School on the Rhine",
    "tms-badoldesloe.de": "TMS Bad Oldesloe",
    "egb-koeln.de": "Erich-Gutenberg Berufskolleg",
    "bs2pa.de": "Staatliche Berufsschule 2 Passau",
    "tu-dortmund.de": "Technische Universität Dortmund TU Dortmund University",
    "uni-jena.de": "Friedrich-Schiller Universität Jena",
    "stw.de": "Steinbeis-Hochschule-Berlin",
    "th-brandenburg.de": "Technische Hochschule Brandenburg",
    "lls-bad.de": "Louis-Lepoix-Schule",
    "fh-wedel.de": "Fachhochschule Wedel",
    "ohg-bensberg.de": "Otto-Hahn-Gymnasium Bergisch Gladbach - Bensberg",
    "obs-ganderkesee.de": "Oberschule Ganderkesee",
    "leo-statz-berufskolleg.de": "Leo-Statz-Berufskolleg we'll use webstorm in this course of study: https://www.leo-statz-berufskolleg.de/bildungsangebot/kfm-assistentin-fuer-informationsverarbeitung",
    "isdedu.de": "International School of Düsseldorf",
    "sbs-herzogenaurach.de": "SBS Herzogenaurach-Höchstadt www.sbs-herzogenaurach.de",
    "whg-lu.de": "Wilhelm-von-Humboldt-Gymnasium",
    "igs-del.de": "IGS Delmenhorst",
    "hof-university.de": "Hochschule für Angewandte Wissenschaften Hof",
    "mh-hannover.de": "Medizinische Hochschule Hannover",
    "uniklinik-freiburg.de": "University Medical Center University of Freiburg",
    "gymhum.de": "Gymnasium Hummelsbüttel",
    "obs1celle.de": "Oberschule Celle 1",
    "rfh-koeln.de": "Rheinische Fachhochschule Köln",
    "hs-ruhrwest.de": "Hochschule Ruhr West",
    "diploma.de": "DIPLOMA-Fachhochschule Ölsnitz/Vogtland Fachhochschule Nordhessen",
    "uni-hannover.de": "Universität Hannover",
    "th-deg.de": "Technische Hochschule Deggendorf",
    "tu-freiberg.de": "Technische Universität Bergakademie Freiberg",
    "klara-oppenheimer-schule.de": "Klara-Oppenheimer-Schule Würzburg",
    "ruhr-uni-bochum.de": "Ruhr-Universität Bochum",
    "oth-regensburg.de": "Ostbayerische Technische Hochschule Regensburg",
    "hms-dtzb.de": "Heinrich-Mann-Schule Dietzenbach https://www.hms-dtzb.de/",
    "uni-mainz.de": "Johannes-Gutenberg Universität Mainz",
    "monte-koeln.de": "Montessori Gymnasium Köln",
    "rwth-aachen.de": "Rheinisch Westfälische Technische Hochschule Aachen",
    "fhws.de": "Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt",
    "mu-luebeck.de": "Medizinische Universität Lübeck",
    "mcggehrden.de": "Matthias Claudius Gymnasium Gehrden",
    "knabenrealschule-neumarkt.de": "Staatliche Knabenrealschule",
    "gbgrs.de": "Gertrud-Bäumer-Gymnasium Gertrud-Bäumer-Gymnasium",
    "zi-mannheim.de": "Central Institute of Mental Health Medical faculty Mannheim University of Heidelberg",
    "efh-freiburg.de": "Evangelische Fachhochschule Freiburg, Hochschule für Soziale Arbeit, Diakonie und Religionspädagogik",
    "jkgc.de": "Johannes-Kepler-Gymnasium Chemnitz",
    "htw-dresden.de": "Hochschule für Technik und Wirtschaft Dresden (FH)",
    "bbs-westerburg.de": "BBS Westerburg HBFI Westerburg",
    "gymneureut.de": "Gymnasium Neureut",
    "rsplus-nierstein.de": "Carl-Zuckmayer-Realschule Plus und Fachoberschule Nierstein",
    "elektronikschule.de": "Elektronikschule Tettnang",
    "berufskolleg-geilenkirchen.de": "Berufskolleg Ernaehrung, Sozialwesen, Technik des Kreises Heinsberg in Geilenkirchen",
    "helmholtz-muenchen.de": "Helmholtz Zentrum München",
    "gbsleipzig.de": "GBS Fachschule für Technik und Wirtschaft GBS Professional School of Technology and Business Administration",
    "caeci-ol.de": "Gymnasium Cäcilienschule Oldenburg",
    "fau.de": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
    "berufskolleg-borken.de": "Berufskolleg Borken Berufskolleg Borken",
    "burg-halle.de": "Burg Giebichenstein Kunsthochschule Halle",
    "oth-aw.de": "Ostbayerische Technische Hochschule Amberg-Weiden",
    "db-gym.de": "Dietrich-Bonhoeffer-Gymnasium Ahlhorn",
    "bsz-eoplauen.de": "Berufliches Schulzentrum e.o.plauen",
    "gyfa-hh.de": "Gymnasium Farmsen",
    "kgw-duisburg.de": "Kopernikus Gymnasium Walsum",
    "mein-gaussge.de": "Carl-Friedrich-Gauß-Gymnasium Gelsenkirchen, Germany gaussge.de (school domain / homepage) mein-gaussge.de (the school's learning platform, used for email)",
    "hmt-leipzig.de": "Hochschule für Musik und Theater Leipzig University of Music and Theatre Leipzig",
    "mycorvey.de": "Gymnasium Corveystraße high school Corveystraße",
    "fhwt.de": "Private Fachhochschule für Wirtschaft und Technik Vechta/Diepholz",
    "rsnibelungen.de": "Nibelungen-Realschule",
    "uni-giessen.de": "Justus Liebig Universität Gießen",
    "mdc-berlin.de": "Max-Delbrück-Centrum für Molekulare Medizin Graduate School",
    "fh-nuernberg.de": "Georg-Simon-Ohm-Fachhochschule Nürnberg",
    "bcw-gruppe-net.de": "bcw-gruppe-net",
    "myhss.de": "Hubert-Sternberg-Schule Wiesloch",
    "dzne.de": "Deutsches Zentrum für Neurodegenerative Erkrankungen, (DZNE) German Center for Neurodegenerative Diseases",
    "wvsi.de": "Werner-von-Siemens-Schule",
    "burggymnasium-altena.de": "Burggymnasium Altena",
    "das-mgh-hamm.de": "Name: Märkisches Gymnasium Hamm / MGH Hamm",
    "bbs1emd.de": "Berufsbildende Schulen I Emden",
    "gymlgh.de": "Gymnasium Langenhagen",
    "gymburlo.de": "Gymnasium Mariengarden Mariengarden high school",
    "marienschule-bielefeld.de": "Marienschule Bielefeld",
    "mpi-cbg.de": "Max Planck Institute of Molecular Cell Biology and Genetics",
    "fh-worms.de": "Fachhochschule Worms",
    "tum.de": "Technical University of Munich",
    "alstergymnasium.de": "Alster Gymnasium",
    "udk-berlin.de": "Universität der Künste Berlin",
    "hwr-berlin.de": "HWR Berlin - Hochschule für Wirtschaft und Recht Berlin (Berlin School of Economics and Law)",
    "fgs-bln.de": "Friedenauer Gemeinschaftsschule",
    "thu.de": "Technische Hochschule Ulm Ulm University of Applied Science",
    "uni-saarland.de": "Universität des Saarlandes",
    "bits-iserlohn.de": "BiTS - Business and Information Technology School gGmbH",
    "bk-technik-moers.de": "Berufskolleg für Technik Moers",
    "ph-erfurt.de": "Pädagogische Hochschule Erfurt/Mühlhausen",
    "karlshochschule.de": "Karlshochschule International University",
    "bbs-me.de": "BBS-ME – Otto-Brenner-Schule",
    "evb-gymnasium.de": "Städtisches Engelbert-von-Berg-Gymnasium Engelbert-von-Berg-Gymnasium EvB-Gymnasium",
    "bs1traunstein.de": "Staatliche Berufsschule 1 Traunstein",
    "hs-augsburg.de": "Technische Hochschule Augsburg Augsburg University of Applied Sciences",
    "fkggoettingen.de": "Felix Klein Gymnasium Göttingen Felix Klein Gymnasium Göttingen (Germany)",
    "osz-teltow.de": "Oberstufenzentrum Technik Teltow OSZ Teltow",
    "kh-berlin.de": "Kunsthochschule Berlin-Weissensee, Hochschule für Gestaltung",
    "uni-marburg.de": "Philipps-Universität Marburg",
    "ms-muc.de": "Meisterschulen am Ostbahnhof, München Master Schools at Ostbahnhof, Munich, Germany",
    "cato-achim.de": "Cato Bontjes van Beek-Gymnasium",
    "bs-an.de": "Staatliche Berufsshule I Ansbach",
    "schulen-fulda.de": "Ferdinand-Braun-Schule Fulda",
    "gym-lachendorf.de": "Immanuel-Kant-Gymnasium Lachendorf",
    "tu-braunschweig.de": "Technische Universität Carolo-Wilhelmina zu Braunschweig",
    "gaussschule-bs.de": "Gaußschule - Gymnasium am Löwenwall",
    "hfpv-hessen.de": "Hessian University of Applied Sciences for Police and Public Administration Hessische Hochschule für Polizei und Verwaltung",
    "dv-schulen.de": "Städtische Berufsfachschule für IT-Berufe Städtische Berufsfachschule für Büroberufe Städtische Berufsfachschule für Kaufmännische Assistenten Städtische Fachschule für Datenverarbeitung Städtische Wirtschafsschule Außenstelle Grombühl .group",
    "ass-vs.de": "Albert-Schweitzer-Schule",
    "hnee.de": "Eberswalde University for Sustainable Development",
    "rheinahrcampus.de": "Hochschule Koblenz Rhein-Ahr-Campus",
    "fh-mainz.de": "Fachhochschule Mainz",
    "wak-sh.de": "Wirtschaftsakademie Schleswig-Holstein",
    "bt-office.de": "Berufskolleg für Technik des Kreis Borken",
    "ruhr-gymnasium.de": "Ruhr-Gymnasium Witten",
    "uni-erlangen.de": "Friedrich-Alexander Universität Erlangen-Nürnberg",
    "hs-zigr.de": "Hochschule Zittau/Görlitz (FH)",
    "berlin-international.de": "Berlin International University of Applied Sciences",
    "flachsland-hamburg.de": "Flachsland Zukunftsschulen",
    "mpg-ka.de": "Max-Planck-Gymnasium Karlsruhe",
    "wvss-wetzlar.de": "Werner-von-Siemens-Schule Wetzlar",
    "mvl-gym.de": "Maria von Linden Gymnasium",
    "tha.de": "Technische Hochschule Augsburg Augsburg University of Applied Sciences",
    "hs-mannheim.de": "Mannheim University of Applied Sciences",
    "aloberlin.de": "Annedore-Leber-Berufsbildungswerk Annedoore-Leber Vocational School",
    "fh-deggendorf.de": "Fachhochschule Deggendorf/Deggendorf Institute of Technology Domain:th-deg.de Email: ..@stud.th-deg.de Email: ..@th-deg.de",
    "rfgs.de": "Richard Fehrenbach Gewerbeschule",
    "imtek.de": "Institut für Mikrosystemtechnik - IMTEK Albert-Ludwigs-Universität Freiburg",
    "lgbk.de": "Lessing Gymnasium | Berufskolleg",
    "fjm-siegen.de": "Fürst-Johann-Moritz Gymnasium FJM",
    "bfw-koeln.de": "Berufsförderungswerk Köln",
    "fos2-n.de": "Staatliche Fachoberschule II",
    "ligcux.de": "Lichtenberg-Gymnasium Cuxhaven",
    "igs-wedemark.de": "IGS Wedemark",
    "fh-biberach.de": "Fachhochschule Biberach, Hochschule für Bauwesen und Wirtschaft",
    "uni-passau.de": "Universität Passau",
    "dshs-koeln.de": "Deutsche Sporthochschule Köln",
    "kisd.de": "KISD - Köln International School of Design",
    "naturkundemuseum-bw.de": "Staatliches Museum für Naturkunde Stuttgart",
    "fh-heilbronn.de": "Fachhochschule Heilbronn, Hochschule für Technik und Wirtschaft",
    "fh-ludwigshafen.de": "Fachhochschule Ludwigshafen, Hochschule für Wirtschaft",
    "hs-worms.de": "Hochschule Worms University of Applied Sciences",
    "ars-mr.de": "Adolf Reichwein Schule",
    "fh-potsdam.de": "Fachhochschule Potsdam",
    "unibw-muenchen.de": "Universität der Bundeswehr München",
    "franziskusgymnasium-it.de": "Franziskusgymnasium Lingen (Ems) High School Franziskusgymnasium Lingen",
    "uni-regensburg.de": "Universität Regensburg",
    "gymn-benedictinum.de": "Gymnasium der Benediktiner, Meschede",
    "htwg-konstanz.de": "Hochschule Konstanz University of Applied Sciences",
    "htw-saarland.de": "Hochschule für Technik und Wirtschaft des Saarlandes",
    "ceg-erlangen.de": "Christian-Ernst-Gymnasium",
    "schulverbund.de": "Isar-Gymnasium München",
    "berufsschule-fs.de": "Berufsschule Freising",
    "fes-wiesbaden.de": "Friedrich-Ebert-Schule Wiesbaden Friedrich-Ebert-School Wiesbaden",
    "th-nuernberg.de": "Technische Hochschule Nürnberg Georg Simon Ohm",
    "uni-bielefeld.de": "Universität Bielefeld",
    "isnm.de": "International School of New Media, University of Lübeck",
    "mbs-altona.de": "Max-Brauer-Schule",
    "esz-radebeul.de": "Evangelisches Schulzentrum Radebeul",
    "ggs-duisburg.de": "Green Gesamtschule",
    "otto-nagel-gymnasium.de": "Otto-Nagel-Gymnasium",
    "uni-wuppertal.de": "Bergische Universität Gesamthochschule Wuppertal Kirchliche Hochschule Wuppertal",
    "febb.de": "FEBB (Freie Evangelische Bekenntnis Schule Bremen)",
    "fh-erfurt.de": "Fachhochschule Erfurt",
    "fhtw-berlin.de": "Fachhochschule für Technik und Wirtschaft Berlin",
    "bbbk.de": "Bertolt-Brecht-Berufskolleg",
    "uni-halle.de": "Martin-Luther-Universität Halle-Wittenberg Martin Luther University Halle-Wittenberg",
    "hss-wi.de": "Hubert-Sternberg-Schule Wiesloch",
    "ibs-ol.de": "IBS IT & Business School Oldenburg e. V. Berufsakademie für IT & Wirtschaft Oldenburg",
    "edvw.de": "EDV-Schule Wiesau",
    "itc-studenten.de": "IT-Center Dortmund",
    "gymbu.de": "Gymnasium Burgdorf",
    "bbq.de": "BBQ - Baumann Bildung und Qualifizierung",
    "hs-nordhausen.de": "Hochschule Nordhausen",
    "hochschule-rhein-waal.de": "Hochschule Rhein-Waal",
    "dhbw-ravensburg.de": "Duale Hochschule Baden-Württemberg Ravensburg",
    "gym-papenburg.de": "Gymnasium Papenburg",
    "bkt-luedenscheid.de": "Berufskolleg für Technik des Märkischen Kreises in Lüdenscheid",
    "uni-vechta.de": "Hochschule Vechta",
    "uni-potsdam.de": "Universität Potsdam",
    "mk-bs.de": "Martino-Katharineum Gymnasium Martino-Katharineum high school",
    "fh-hamburg.de": "Fachhochschule Hamburg",
    "efh-hannover.de": "Evangelische Fachhochschule Hannover",
    "ph-heidelberg.de": "Pädagogische Hochschule Heidelberg",
    "hs-lu.de": "Hochschule Ludwigshafen am Rhein",
    "uni-ulm.de": "Universität Ulm",
    "schulzentrum-am-sund.de": "Schulzentrum am Sund",
    "ghse.de": "Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen",
    "ku-eichstaett.de": "Katholische Universität Eichstätt",
    "hfm-detmold.de": "Hochschule für Musik Detmold University for Music Detmold",
    "semper-schueler.de": "Semper Fachoberschule Dresden",
    "rvwbk.de": "Richard-von-Weizsäcker-Berufskolleg",
    "ba-sachsen.de": "Berufsakademie Sachsen Staatliche Studienakademie Leipzig",
    "fh-brandenburg.de": "Technische Hochschule Brandenburg",
    "schweinfurt.de": "Dr.-Georg-Schäfer-Schule",
    "hs-neu-ulm.de": "Hochschule Neu Ulm University of applied sciences",
    "rauheshaus.de": "Evangelische Fachhochschule für Sozialpädagogik der Diakonenanstalt des Rauhen Hauses Hamburg",
    "erasmus-kittler-schule.de": "Erasmus-Kittler-Schule, Darmstadt",
    "oszimt.de": "Oberstufenzentrum Informations- und Medizintechnik",
    "ks-ldk.de": "Kaufmännische Schulen Dillenburg",
    "obs-weener.de": "Oberschule Weener",
    "privatfh-da.de": "Private FernFachhochschule Darmstadt",
    "hs-hannover.de": "Hochschule Hannover",
    "wgg-neumarkt.de": "Willibald-Gluck-Gymnasium",
    "cased.de": "Center for Advanced Security Research Darmstadt",
    "hs21.de": "Hochschule 21/Buxtehude (FH)",
    "gs-wn.de": "Gewerbliche Schule Waibligen",
    "hft-leipzig.de": "Deutsche Telekom University of Applied Sciences Leipzig",
    "bbs-wittlich.de": "Berufsbildende Schule Wittlich",
    "gewerbeschule-vs.de": "Gewerbeschule villingen Schwenningen",
    "bbs-verden.de": "BBS Verden",
    "mh-trossingen.de": "Staatliche Hochschule für Musik",
    "rhein-gymnasium-sinzig.de": "Rhein-Gymnasium Sinzig",
    "fom-net.de": "Fachhochschule für Oekonomie und Management (FOM)",
    "wrs-lueneburg.de": "Wilhelm Raabe Schule",
    "mwn.de": "Hochschule für Philosophie München",
    "ba-fulda.de": "Private Berufsakademie Fulda University of Cooperative Education http://www.ba-fulda.de",
    "hs-gm.de": "Hochschule Geisenheim University",
    "freie-georgenschule.de": "Freie Georgenschule",
    "spranger-hamm.de": "Eduard Spranger Berufskolleg Hamm www.esb-hamm.de",
    "schule-ge-velbert.de": "Gesamtschule Velbert-Mitte",
    "drais-schule.de": "Drais-Gemeinschaftsschule",
    "mlg-bad.de": "Markgraf-Ludwig-Gymnasium Baden-Baden",
    "bbs-ohz.de": "Berufsbildende Schulen Osterholz-Scharmbeck",
    "hochschule-trier.de": "Trier University of Applied Sciences",
    "embl.de": "European Molecular Biology Laboratory EMBL, Heidelberg URL: https://www.embl.de/ Courses: https://www.embl.de/training/index.php",
    "lindengymnasium.de": "Staedtisches Lindengymnasium Gummersbach",
    "bsutaunus.de": "Berufliche Schulen Untertaunus",
    "leuphana.de": "Leuphana Universität Lüneburg",
    "augustana.de": "Augustana Hochschule Neuendettelsau",
    "fh-swf.de": "Fachhochschule Südwestfalen",
    "rs-leimen.de": "Otto-Graf Realschule",
    "tel-ran.de": "Tel-Ran.de",
    "htw-berlin.de": "University of Applied Sciences, Berlin",
    "fh-weihenstephan.de": "Fachhochschule Weihenstephan",
    "gymnasium-heiligenhaus.de": "Immanuel-Kant-Gymnasium Heiligenhaus",
    "th-koeln.de": "Fachhochschule Köln Technische Hochschule Köln",
    "fzi.de": "Forschungszentrum Informatik FZI Research Center for Information Technology",
    "johanneum-lg.de": "Johanneum Lüneburg",
    "htwk-leipzig.de": "Hochschule für Technik, Wirtschaft und Kultur Leipzig (FH)",
    "hds-le.de": "Heinrich-Drake-Schule Lemgo",
    "fhm-mittelstand.de": "Fachhochschule des Mittelstandes (FHM)",
    "fh-karlsruhe.de": "Fachhochschule Karlsruhe, Hochschule für Technik",
    "muthesius.de": "Muthesius-Hochschule, Fachhochschule für Kunst und Gestaltung",
    "bk-tm.de": "Berufskolleg Platz der Republik fur Technik und Medien",
    "fh-luebeck.de": "Fachhochschule Lübeck",
    "athenetz.de": "Gymnasium Athenaeum Stade",
    "ukbonn.de": "Universitätsklinikum Bonn University Hospital Bonn",
    "berufskolleg.de": "Berufskolleg Hilden des Kreises Mettmann Berufskolleg Hilden",
    "tagore-gymnasium.de": "Tagore-Gymnasium",
    "utn.de": "Technische Universität Nürnberg",
    "dhbw-loerrach.de": "Duale Hochschule Baden-Württemberg Lörrach",
    "ohg-sb.de": "Otto-Hahn-Gymnasium Saarbrücken",
    "ib-hochschule.de": "IB Hochschule Berlin IB University Berlin",
    "inntal-gymnasium.de": "Inntal-Gymnasium, Raubling Inntal High School, Raubling",
    "uni-bonn.de": "Rheinische Friedrich-Wilhelms Universität Bonn University of Bonn",
    "bs-korbach.de": "Berufliche Schulen des Landkreises Waldeck-Frankenberg in Korbach und Bad Arolsen AöR",
    "gymnasium-essen-werden.de": "Gymnasium Essen-Werden",
    "donau-gymnasium.de": "Donau-Gymnasium in Kelheim",
    "iserv-gis.de": "Gymnasium im Schloss Wolfenbüttel",
    "igs-seevetal.de": "IGS Seevetal",
    "wss-stuttgart.de": "Werner Siemens Schule Stuttgart Werner Siemens Technical School Stuttgart",
    "rbbk-do.de": "Robert-Bosch-Berusfkolleg",
    "ba-leipzig.de": "Berufsakademie Leipzig",
    "hpi.de": "Hasso Plattner Institute",
    "itech-bs14.de": "Berufliche Schule ITECH Elbinsel Wilhelmsburg (BS14) Vocational school ITECH Elbinsel Wilhelmsburg (BS14)",
    "hs-coburg.de": "Hochschule Coburg",
    "kmgfn.de": "Karl-Maybach-Gymnasium Friedrichshafen",
    "vit-bund.de": "Federal University of Applied Administrative Sciences > Departmental Branch of Financial Administration > degree course: administrative information systems",
    "whg-duew.de": "Werner-Heisenberg-Gymnasium Bad Dürkheim",
    "hs-niederrhein.de": "Hochschule Niederrhein",
    "cit-leipzig.de": "CiT Leipzig",
    "atiw.de": "ATIW Berufskolleg",
    "bwv-ahaus.de": "Berufskolleg Wirtschaft und Verwaltung Ahaus",
    "gesa-soest.de": "Hannah-Arendt-Gesamtschule Soest",
    "fh-hannover.de": "Fachhochschule Hannover",
    "hs-ansbach.de": "Ansbach University of Applied Sciences",
    "hg-gf.de": "Humboldt-Gymnasium Gifhorn",
    "neuefische.de": "neuefische - School and Pool for Digital Talent",
    "fh-jena.de": "Fachhochschule Jena",
    "uni-hamburg.de": "Universität Hamburg",
    "ebs.de": "European Business School Schloß Reichartshausen",
    "ems-mainz.de": "European Management School",
    "dkfz-heidelberg.de": "DKFZ Heidelberg",
    "fh-oow.de": "Fachhochschule Oldenburg/Ostfriesland/Wilhelmshaven",
    "e-b-z.de": "Europäisches Bildungszentrum der Wohnungs- und Immobilienwirtschaft (EBZ)- gemeinnützige Stiftung",
    "lernsax.de": "School: Schülerrechenzentrum Dresden E-Mail-Suffix: srz.lernsax.de Proof that this school use this mail provider: On the page lernsax.de is on the left side a botton with the text \"LernSax Kennenlernen\" it means get to know lernsax. You have to click this button. On this new page is on the left side a botton with the text \"Karte der LernSax-Nutzer\" it shows you a map of the lernsax users. On this map you have to click this circle (https://prnt.sc/1ak5py1). Click the \"Impressium\" (inprint) botton to check if the school website is ewvt.de",
    "gsz-zak.de": "Philipp-Matthäus-Hahn-Schule – Gewerbliches Schulzentrum Balingen",
    "bbs2-northeim.de": "BBS 2 Northeim",
    "gymlil.de": "Gymnasium Lilienthal",
    "gymbuckhorn.de": "Gymnasium Buckhorn",
    "bethel.de": "Kirchliche Hochschule Bethel",
    "uni-heidelberg.de": "Hochschule für Jüdische Studien Heidelberg Ruprecht-Karls-Universität Heidelberg",
    "hs-bremerhaven.de": "Hochschule Bremerhaven",
    "dgk-keh.de": "Donau Gymnasium Kelheim",
    "uni-muenster.de": "Westfälische Wilhelms-Universität Münster",
    "ge-meiersheide.de": "Gesamtschule Hennef Meiersheide",
    "ohggf.de": "Otto-Hahn-Gymnasium",
    "grimmels.de": "Name: Grimmelshausen Gymnasium Gelnhausen Website: http://grimmels.de/wordpress/ Computer science course: http://grimmels.de/wordpress/qualifikationsphase/ (Proof that is it offered as intensive course: On the site jump to: E > Kursangebot des GGG > Leistungsfächerangebot > Aufgabenfeld III > Informatik ) Email proof: http://grimmels.de/wordpress/kontakte/",
    "fham.de": "Hochschule für angewandtes Management - Ismaning/München University of Applied Management - Ismaning/Munich",
    "osz-biv.de": "EWF Europäische Wirtschaftsfachschule Berlin",
    "theresianum-mainz.de": "Gymnasium Theresianum Mainz",
    "hshl.de": "Hochschule Hamm-Lippstadt",
    "hs-aalen.de": "Hochschule Aalen",
    "hfmt-hamburg.de": "Hochschule für Musik und Theater Hamburg Music and Theater College in Hamburg",
    "fh-wuerzburg.de": "Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt",
    "rub.de": "Ruhr-Universität Bochum",
    "hwg-lu.de": "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen",
    "gottfried-kinkel-realschule.de": "Gottfried Kinkel Realschule Gottfried Kinkel Realschule",
    "berufskolleg-rheine.de": "Berufskolleg Rheine des Kreises Steinfurt",
    "hamburger-fh.de": "Hamburger Fern-Hochschule (HFH)",
    "rsh-duesseldorf.de": "Robert Schumann Hochschule Düsseldorf Robert Schumann University of Music and Media",
    "hhg-kl.de": "Staatliches Heinrich-Heine-Gymnasium Kaiserslautern",
    "bbst-clp.de": "Berufsbildende Schule Technik Cloppenburg",
    "hdbw-hochschule.de": "Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften (HDBW) gGmbH University of the Bavarian Economy for Applied Sciences (HDBW)",
    "ba-dresden.de": "Berufsakademie Sachsen Staatliche Studienakademie Dresden",
    "bfw-leipzig.de": "Berufsförderungswerk Leipzig gemeinnützige GmbH Berufsförderungswerk Leipzig BFW Leipzig",
    "h-ka.de": "Karlsruhe University of Applied Sciences",
    "fh-bingen.de": "Fachhochschule Bingen",
    "pdr-kelkheim.de": "Privatgymnasium Dr. Richter",
    "bs7-augsburg.de": "Berufsschule 7 Career School 7",
    "hhek.de": "Heinrich Hertz Europakolleg",
    "uni-a.de": "Universität Augsburg Augsburg University",
    "ohg-boeblingen.de": "Otto-Hahn-Gymnasium Böblingen",
    "fh-aschaffenburg.de": "Fachhochschule Aschaffenburg",
    "geestnetz.de": "Geestlandschule",
    "fh-isny.de": "Fachhochschule und Berufskollegs NTA, Prof.Dr. Grübler gemein. GmbH",
    "fh-ulm.de": "Fachhochschule Ulm, Hochschule für Technik",
    "hs-merseburg.de": "University of Applied Sciences Merseburg",
    "rdg-online.de": "Rudolf Diesel Gymnasium Augsburg",
    "gso-koeln.de": "Georg-Simon-Ohm-Berufskolleg Köln",
    "avs-itzehoe1.de": "Auguste-Viktoria-Schule Itzehoe, Hs. 1",
    "igs-sassenburg.de": "IGS Sassenburg Integriertegesamtschule Sassenburg",
    "th-wildau.de": "Wildau Technical University of Applied Sciences",
    "tu-chemnitz.de": "Technische Universität Chemnitz-Zwickau",
    "ge-walsum.de": "Gesamtschule Walsum",
    "ernestinum-rinteln.de": "Gymnasium Ernestinum Rinteln",
    "hs-kempten.de": "Hochschule für angewandte Wissenschaften Kempten University of Applied Sciences Kempten",
    "fht-stuttgart.de": "Fachhochschule Stuttgart, Hochschule für Technik",
    "aagcux.de": "Amandus-Abendroth-Gymnasium Cuxhaven",
    "wbsedu.de": "WBS TRAINING AG",
    "technikerschule-berlin.de": "Staatliche Technikerschule Berlin",
    "ipu.de": "International Psychoanalytic University",
    "hfpol-bw.de": "Hochschule für Polizei Baden-Württemberg",
    "hn.de": "Hochschule Niederrhein",
    "uni-hohenheim.de": "Universität Hohenheim",
    "hs-osnabrueck.de": "University Of Osnabrück",
    "hgb-leipzig.de": "Academy of Visual Arts Leipzig",
    "hs-duesseldorf.de": "Hochschule Düsseldorf",
    "ftsvs.de": "Staatliche Feintechnikschule mit Technischem Gymnasium Schwenningen",
    "brand-university.de": "Brand University of Applied Sciences, Hamburg, Germany",
    "bbs2-mainz.de": "Sophie Scholl Schule Mainz",
    "bbs-meppen.de": "Berufsbildende Schulen Meppen",
    "iserv-herderschule-giessen.de": "Herderschule Gießen",
    "ba-riesa.de": "Berufsakademie Sachsen Staatliche Studienakademie Riesa",
    "sz-uetze.de": "Gymnasium unter den Eichen Uetze",
    "bbs2.de": "Berufsbildende Schule 2 Delmenhorst (BBS 2 Delmenhorst) Kerschensteiner School Delmenhorst",
    "hswt.de": "Weihenstephan-Triesdorf University of Applied Sciences",
    "ecla.de": "European College of Liberal Arts",
    "cjd-elz.de": "CJD Christophorusschule Elze - Gymnasium",
    "hfm-karlsruhe.de": "University of Music Karlsruhe",
    "hs-wismar.de": "Hochschule Wismar, Fachhochschule für Technik, Wirtschaft und Gestaltung",
    "gbg-remscheid.de": "Gertrud-Bäumer-Gymnasium Gertrud-Bäumer-Gymnasium",
    "hwos.de": "Hildegard-Wegscheider-Gymnasium",
    "bbssth.de": "Berufsbildende Schule Stadthagen vocational schools Stadthagen",
    "ihi-zittau.de": "Internationales Hochschulinstitut Zittau",
    "tfh-wildau.de": "Technische Fachhochschule Wildau",
    "hfwu.de": "Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen",
    "tfh-berlin.de": "Technische Fachhochschule Berlin",
    "hsw-stud.de": "Hochschule Weserbergland",
    "uni-paderborn.de": "Universität Paderborn",
    "kfh-Freiburg.de": "Katholische Fachhochschule Freiburg, Hochschule für Sozialwesen, Religionspädagogik und Pflege",
    "geskn.de": "Gesamtschule Kürten Kürten Comprehensive School",
    "hbksaar.de": "Hochschule der Bildenden Künste Saar",
    "fh-nuertingen.de": "Fachhochschule Nürtingen, Hochschule für Wirtschaft, Landwirtschaft und Landespflege",
    "khgmettmann.de": "Konrad-Heresbach-Gymnasium Mettmann",
    "gymbla.de": "Gymnasium Blankenese",
    "ism-dortmund.de": "International School of Management ISM Dortmund",
    "itc-dortmund.de": "IT-Center Dortmund",
    "kfb-berlin.de": "Katholische Fachhochschule Berlin (KFB)",
    "bsz-vogtland.de": "Berufliches Schulzentrum Vogtland Vogtland Vocational School Center for business and IT",
    "fh-offenburg.de": "Fachhochschule Offenburg, Hochschule für Technik und Wirtschaft",
    "log-web.de": "Lichtenberg-Oberstufen-Gymnasium Bruchköbel",
    "berufsakademie-oldenburg.de": "Berufsakademie Oldenburg",
    "wvo-dbg.de": "Wilhelm von Oranien Schule",
    "dhsh.de": "Berufsakademie Schleswig-Holstein",
    "rhs-bs.de": "Ricarda-Huch-Schule Braunschweig",
    "ts-aalen.de": "Technische Schule Aalen",
    "kitz-heidelberg.de": "Hopp Children's Cancer Center Heidelberg (KiTZ) Heidelberg University Hospital and the German Cancer Research Center (DKFZ)",
    "b3-fuerth.de": "Martin-Segitz-Schule / Staatliche Berufsschule III Fürth Martin-Segitz-Schule / State vocational school III Fürth",
    "semper-schulen.de": "Semper Schulen",
    "gesa-rhede.de": "Gesamtschule Rhede Rhede comprehensive school",
    "efh-reutlingen-ludwigsburg.de": "Evangelische Fachhochschule Reutlingen-Ludwigsburg, Hochschule für Soziale Arbeit, Religionspädagogik und Diakonie",
    "shg-hi.de": "Scharnhorstgymnasium Hildesheim",
    "fh-neu-ulm.de": "Fachhochschule Neu-Ulm",
    "gymsas.de": "Sankt-Ansgar-Schule Hamburg",
    "g18.de": "Staatliche Gewerbeschule G18 - Technical College G18",
    "upb.de": "University of Paderborn",
    "sp-gs.de": "Sally Perel Gesamtschule Sally Perel Comprehensive School",
    "hhu.de": "Heinrich Heine University Düsseldorf",
    "hochschule-heidelberg.de": "SRH Hochschule Heidelberg",
    "igs-kastellaun.de": "Integrierte Gesamtschule Kastellaun",
    "sus-bbswhs.de": "Berufliches Gymnasium Wildeshausen",
    "hwp-hamburg.de": "HWP - Hamburger Universität für Wirtschaft und Politik",
    "bbs-nienburg.de": "Berufsbildende Schulen des Landkreises Nienburg/Weser",
    "gbs-sha.de": "Gewerbliche Schule Schwäbisch Hall",
    "max-planck-ge.de": "Max-Planck-Gymnasium Gelsenkirchen-Buer",
    "schulen-hannover.de": "schulen-hannover.de",
    "buhmann-hannover.de": "Dr. Buhmann Schule & Akademie Hannover Dr. Buhmann School & Academy Hanover",
    "fh-bonn-rhein-sieg.de": "Fachhochschule Bonn-Rhein-Sieg",
    "hszg.de": "Hochschule Zittau/Görlitz (FH)",
    "uni-frankfurt.de": "Johann Wolfgang Goethe Universität Frankfurt am Main Philosophisch-Theologische Hochschule Sankt Georgen",
    "hochtaunusschule.de": "Hochtaunusschule Oberursel",
    "uni-trier.de": "Theologische Fakultät Trier Universität Trier",
    "genoveva.de": "Genoveva gymnasium",
    "bs-intra.de": "Staatliches Berufliches Schulzentrum Roth",
    "bbwa-abensberg.de": "BBW Abensberg Abensberg vocational training center (loose translation)",
    "kvgg.de": "Kardinal-von-Galen-Gymnasium Kevelaer",
    "bszn-da.de": "Berufsschulzentrum Nord Darmstadt",
    "asfh-berlin.de": "Alice-Salomon-Fachhochschule für Sozialarbeit und Sozialpädagogik Berlin",
    "whu-koblenz.de": "Wissenschaftliche Hochschule für Unternehmensführung, Otto-Beisheim Hochschule",
    "hgs-singen.de": "Hohentwiel Gewerbeschule Singen",
    "fh-rosenheim.de": "Fachhochschule Rosenheim, Hochschule für Technik und Wirtschaft",
    "jacobs-university.de": "Jacobs University Bremen",
    "fernuni-hagen.de": "Fernuniversität Gesamthochschule Hagen",
    "ksfh.de": "Katholische Stiftungsfachhochschule München",
    "kvg-mettingen.de": "Kardinal von Galen Gymnasium Mettingen",
    "hcu-hamburg.de": "Hafencity Universität Hamburg",
    "th-rosenheim.de": "Technische Hochschule Rosenheim Technical University Of Applied Sciences Rosenheim",
    "heinrichheinedo.de": "Heinrich-Heine-Gymnasium Dortmund",
    "fh-aalen.de": "Internationale Fachhochschule Aalen",
    "stud-provadis-hochschule.de": "Provadis School of International Management and Technology AG, 65926 Frankfurt am Main",
    "hdm-stuttgart.de": "Fachhochschule Stuttgart, Hochschule der Medien",
    "ostfalia.de": "Ostfalia Hochschule für angewandte Wissenschaften",
    "ratsgympeine.de": "Ratsgymnasium Peine",
    "cbk1.de": "Cuno-Berufskolleg I",
    "goegy.de": "Goethe-Gymnasium Regensburg Goethe-Gymnasium Regensburg",
    "fli.de": "Friedrich-Loeffler-Institut",
    "cbw-onlineschulung.de": "CBW - College Berufliche Weiterbildung GmbH",
    "berufsakademie-sh.de": "Berufsakademie Schleswig-Holstein",
    "ids-mannheim.de": "Leibniz-Institut für Deutsche Sprache",
    "hhgym.de": "Heinrich-Hertz-Gymnasium Berlin",
    "hans-baldung-gymnasium.de": "Hans-Baldung-Gymnasium",
    "rak.de": "RHEINISCHE AKADEMI KÖLN https://www.rak.de https://www.rak.de/die-rak/service-fuer-schueler-und-studierende/",
    "uni-erfurt.de": "Philosophisch-Theologisches Studium Erfurt, Staatlich anerkannte Wissenschaftliche Hochschule Universität Erfurt",
    "fhkt.de": "Staatlich anerkannte Fachhochschule für Kunsttherapie",
    "fhs-moritzburg.de": "Evangelische Fachhochschule für Religionspädagogik, und Gemeindediakonie Moritzburg",
    "fh-gelsenkirchen.de": "Fachhochschule Gelsenkirchen",
    "pgs-portal.de": "Paul-Gerhardt Schule Dassel",
    "fh-fresenius.de": "Europa Fachhochschule Fresenius",
    "ph-weingarten.de": "Pädagogische Hochschule Weingarten",
    "gemont.de": "Gebrüder-Montgolfier-Gymnasium Berlin",
    "fmg-brk.de": "Franz-Miltenberger-Gymnasium",
    "bbs-schueler.de": "Berufsbildende Schulen Walsrode",
    "noether-gymnasium.de": "Emmy-Noether-Gymnasium",
    "iu-akademie.de": "IU Internationale Hochschule GmbH",
    "htw-aalen.de": "hs-aalen.txt",
    "gesamtschule-fischbach.de": "Gesamtschule Fischbach",
    "amseegym.de": "Ammersee-Gymnasium",
    "gymnasium-marienstatt.de": "Privates Gymnasium Marienstatt",
    "burgaugymnasium.de": "Burgaugymnasium Düren",
    "mfh-iserlohn.de": "Märkische Fachhochschule Iserlohn",
    "fh-weingarten.de": "Fachhochschule Ravensburg-Weingarten",
    "uni-landau.de": "Universität Koblenz-Landau",
    "igs-wunstorf.de": "IGS Wunstorf",
    "hnu.de": "Hochschule Neu Ulm University of applied sciences",
    "gymhaan.de": "Städtisches Gymnasium Haan",
    "uos.de": "University of Osnabrueck",
    "hrsaaf.de": "Schule Altes Amt Friedeburg",
    "sts-old.de": "Stadtteilschule Oldenfelde",
    "schule-schloss-salem.de": "Schule Schloss Salem",
    "mailwb-online-campus.de": "Wilhelm Büchner Hochschule Wilhelm Büchner University",
    "leibniz-fh.de": "Leibniz Fachhochschule",
    "siu-heidelberg.de": "Schiller International University, Heidelberg",
    "fh-mannheim.de": "Fachhochschule Mannheim, Hochschule für Technik und Gestaltung",
    "jprs.de": "Johann-Philipp-Reis-Schule Friedberg (Hessen), Berufliches Gymnasium",
    "rs-ilsede.de": "Realschule Groß Ilsede",
    "kvgschulen.de": "Kardinal von Galen Gymnasium Mettingen",
    "gy-steinheim.de": "Städtisches Gymnasium Steinheim",
    "uni-kiel.de": "Christian-Albrechts-Universität Kiel",
    "gds2.de": "﻿Gottlieb-Daimler-Schule 2 Technisches Schulzentrum Sindelfingen mit Abteilung Akademie für Datenverarbeitung",
    "hit-thueringen.de": "HIT | Akademische Personalentwicklung an Hochschulen in Thüringen hit-thueringen.de",
    "uni-duesseldorf.de": "Heinrich-Heine Universität Düsseldorf",
    "unibw-hamburg.de": "Universität der Bundeswehr Hamburg",
    "uni-wuerzburg.de": "Bayerische Julius-Maximilians-Universität Würzburg",
    "lmu.de": "Ludwig Maximilian University of Munich",
    "iubh.de": "International University of Applied Sciences Bad Honnef - Bonn",
    "hsbi.de": "Hochschule Bielefeld",
    "bfw-oberhausen.de": "Berufsförderungswerk Oberhausen, Primary Domain",
    "bbs-buxtehude.de": "Berufsbildende Schulen Buxtehude",
    "bsz-wiesau.de": "Staatliches Berufliches Schulzentrum Wiesau State Vocational School Center Wiesau",
    "fhoebb.de": "Fachhochschule für das öffentliche Bibliothekswesen Bonn",
    "hs-heilbronn.de": "Hochschule Heilbronn (FH)",
    "lsh-marquartstein.de": "Gymnasium Landschulheim Marquartstein",
    "eufh.de": "Europäische Fachhochschule",
    "sgh-holzgerlingen.de": "Schönbuch Gymnasium Holzgerlingen Pls. add this school in Germany: https://www.schoenbuch-gymnasium.de/sgh/ The short domain the students get IDs for is sgh-holzgerlingen.de",
    "mes-portal.de": "Max Eyth Schule Schiffdorf",
    "pth-bb.de": "Philosophisch-Theologische Hochschule der Salesianer Don Boscos",
    "uni-augsburg.de": "Universität Augsburg",
    "tiho-hannover.de": "Tierärztliche Hochschule Hannover",
    "wilhelm-busch-gymnasium.de": "Wilhelm Busch Gymnasium Stadthagen",
    "schule-franzburg.de": "Regionale Schule mit Grundschule Franzburg",
    "edvschule-plattling.de": "EDV-Schulen des Landkreises Deggendrof",
    "ba-bautzen.de": "Berufsakademie Sachsen Staatliche Studienakademie Bautzen",
    "erasgym.de": "Erasmus Gymnasium",
    "uni-due.de": "University Duisburg-Essen",
    "dhbw-mannheim.de": "Duale Hochschule Baden-Württemberg, Mannheim",
    "h-brs.de": "Bonn-Rhein-Sieg University of Applied Sciences",
    "fls-da.de": "Friedrich-List Schule Darmstadt",
    "hhl.de": "Handelshochschule Leipzig",
    "bbs2leer.de": "BBS 2 Leer",
    "tuhh.de": "Technische Universität Hamburg-Harburg",
    "abendgymnasium-muenster.de": "Abendgymnasium Münster",
    "gymnasium-gag.de": "Graf-Anton-Günther-Schule",
    "bztg-oldenburg.de": "Bildungszentrum für Technik und Gestaltung Oldenburg",
    "uni-wh.de": "Private Universität Witten/Herdecke",
    "mbg-germering.de": "Max-Born-Gymnasium Germering",
    "heinrich-mann-schule.de": "Heinrich-Mann-Schule Dietzenbach https://www.hms-dtzb.de/",
    "bk-technik-dueren.de": "Berufskolleg für Technik Düren https://www.bkt-dueren.de/",
    "igs-ost.de": "Gesamtschule Gießen Ost",
    "johannes-althusius-gymnasium.de": "johannes althusius gymnasium",
    "eah-jena.de": "Ernst-Abbe-Hochschule Jena",
    "wvss2-hildesheim.de": "Werner-von-Siemens-Schule Hildesheim",
    "berufskolleg-werne.de": "Freiherr-vom-Stein Berufskolleg Werne",
    "tu-cottbus.de": "Brandenburgische Technische Universität Cottbus",
    "iserv-schillerschule.de": "Schillerschule Hannover",
    "bimm-institute.de": "BIMM University Berlin"
}
